# 1. Configuración de la conexión a Aiven MySQL (Usando IP para evitar fallos de DNS)
spring.datasource.url=jdbc:mysql://134.209.85.74:27386/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

# 2. Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
